export const GET_VIDEOS = 'GET_VIDEOS';
export const GET_SINGLE_VIDEO = 'GET_SINGLE_VIDEO';
export const GET_SELECTED_VIDEO = 'GET_SELECTED_VIDEO';
export const GET_RELATED_VIDEOS = 'GET_RELATED_VIDEOS';
